#!/usr/bin/env bash

# run command. Will become a dockercompose file eventually
sudo docker run -it \
    --name mymosh \
    --mount type=bind,source=$(dirname $SSH_AUTH_SOCK),target=/ssh-agent \
    --mount type=bind,source=$(dirname $(readlink -f $0)),target=/home/repo \
    $(cat ./env/nametag) \
    /bin/bash