#!/usr/bin/env bash

# run command. Will become a dockercompose file eventually
sudo docker run -it --rm \
    --name mymosh \
    --mount type=bind,source=$SSH_AUTH_SOCK,target=/ssh-agent/ssh \
    --mount type=bind,source=$(dirname $(readlink -f $0)),target=/home/repo \
    --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
    -e CONTAINER_NAME=$(cut ./env/nametag -f1 -d:) \
    $(cat ./env/nametag) \
    /bin/bash
