#!/usr/bin/env bash

mkdir -p /miniconda3
wget https://repo.anaconda.com/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64.sh -O /miniconda3/miniconda.sh
bash /miniconda3/miniconda.sh -b -u -p /miniconda3
rm -rf /miniconda3/miniconda.sh
/miniconda3/bin/conda init bash
/miniconda3/bin/conda init zsh